(()=>{'use strict';
const STATE_KEY='python-ai-definitive-v3',SYNC_KEY='python-ai-backend-sync-v1';
const nativeFetch=window.fetch.bind(window),safeJson=s=>{try{return JSON.parse(s)}catch{return null}};
const readState=()=>safeJson(localStorage.getItem(STATE_KEY)||'null'),readSync=()=>safeJson(localStorage.getItem(SYNC_KEY)||'null')||{backends:{}};
const writeSync=v=>localStorage.setItem(SYNC_KEY,JSON.stringify(v)),normalizeBase=u=>String(u||'').replace(/\/$/,''),apiUrl=(b,p)=>normalizeBase(b)+p;
const fingerprint=value=>{const text=typeof value==='string'?value:JSON.stringify(value);let hash=2166136261;for(let i=0;i<text.length;i++){hash^=text.charCodeAt(i);hash=Math.imul(hash,16777619)}return(hash>>>0).toString(36)};
function bucket(base){const all=readSync(),key=normalizeBase(base);all.backends[key]||={conversations:{},messages:{},memories:{},files:{},fingerprints:{conversations:{},memories:{},files:{}}};const data=all.backends[key];data.fingerprints||={};for(const k of['conversations','memories','files'])data.fingerprints[k]||={};return{all,key,data}}
const persist=ctx=>writeSync(ctx.all);
async function jsonFetch(url,options={}){const r=await nativeFetch(url,options);if(!r.ok)throw Error(`Backend sync HTTP ${r.status}`);return r.status===204?{}:r.json()}
const patchRemote=(base,collection,id,payload)=>jsonFetch(apiUrl(base,`/api/${collection}/${encodeURIComponent(id)}`),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});
const removeRemote=(base,collection,id)=>jsonFetch(apiUrl(base,`/api/${collection}/${encodeURIComponent(id)}`),{method:'DELETE'});
async function reconcileDeleted(base,state,ctx){let changed=false;for(const[collection,items]of[['conversations',state.conversations],['memories',state.memories],['files',state.files]]){if(!Array.isArray(items))continue;const live=new Set(items.map(x=>x?.id).filter(Boolean)),map=ctx.data[collection]||{};for(const[localId,remoteId]of Object.entries(map)){if(live.has(localId))continue;try{await removeRemote(base,collection,remoteId);delete map[localId];delete ctx.data.fingerprints?.[collection]?.[localId];changed=true}catch(e){console.warn(`[Python AI] exclusão remota pendente (${collection}):`,e.message)}}}if(Array.isArray(state.conversations)){const live=new Set();for(const c of state.conversations)for(const m of c?.messages||[])if(m?.id)live.add(m.id);for(const id of Object.keys(ctx.data.messages||{}))if(!live.has(id)){delete ctx.data.messages[id];changed=true}}if(changed)persist(ctx)}
async function ensureConversation(base,state,ctx){const local=state.conversations?.find(c=>c.id===state.activeConversationId);if(!local)return null;const payload={title:(local.title||'Novo chat').slice(0,120),project_id:local.projectId||null},fp=fingerprint([payload.title,payload.project_id]);let remoteId=ctx.data.conversations[local.id],prev=ctx.data.fingerprints.conversations[local.id];if(remoteId&&prev&&prev!==fp){try{await patchRemote(base,'conversations',remoteId,payload);ctx.data.fingerprints.conversations[local.id]=fp;persist(ctx)}catch(e){console.warn('[Python AI] edição de conversa pendente:',e.message)}return remoteId}if(remoteId){if(!prev){ctx.data.fingerprints.conversations[local.id]=fp;persist(ctx)}return remoteId}const remote=await jsonFetch(apiUrl(base,'/api/conversations'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});ctx.data.conversations[local.id]=remote.id;ctx.data.fingerprints.conversations[local.id]=fp;persist(ctx);return remote.id}
async function syncMessages(base,state,ctx,cid){const local=state.conversations?.find(c=>c.id===state.activeConversationId);if(!local||!cid)return;for(const m of local.messages||[]){if(!m?.id||ctx.data.messages[m.id]||m.streaming||!m.content?.trim()||!['user','assistant'].includes(m.role))continue;const remote=await jsonFetch(apiUrl(base,`/api/conversations/${encodeURIComponent(cid)}/messages`),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({role:m.role,content:m.content})});ctx.data.messages[m.id]=remote.id;persist(ctx)}}
async function syncMemories(base,state,ctx){for(const m of state.memories||[]){if(!m?.id||!m.title?.trim()||!m.content?.trim())continue;const payload={title:m.title.slice(0,120),content:m.content.slice(0,20000)},fp=fingerprint([payload.title,payload.content]),remoteId=ctx.data.memories[m.id],prev=ctx.data.fingerprints.memories[m.id];if(remoteId&&prev&&prev!==fp){try{await patchRemote(base,'memories',remoteId,payload);ctx.data.fingerprints.memories[m.id]=fp;persist(ctx)}catch(e){console.warn('[Python AI] edição de memória pendente:',e.message)}continue}if(remoteId){if(!prev){ctx.data.fingerprints.memories[m.id]=fp;persist(ctx)}continue}try{const remote=await jsonFetch(apiUrl(base,'/api/memories'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});ctx.data.memories[m.id]=remote.id;ctx.data.fingerprints.memories[m.id]=fp;persist(ctx)}catch(e){console.warn('[Python AI] memória não sincronizada:',e.message)}}}
function fileForm(file){const form=new FormData();form.append('file',new Blob([file.text],{type:file.type||'text/plain'}),file.name||'arquivo.txt');return form}
async function syncSelectedFiles(base,state,ctx,selectedIds){const selected=new Set(selectedIds||[]),remoteIds=[];if(!selected.size)return remoteIds;for(const file of state.files||[]){if(!selected.has(file.id)||!file.text?.trim())continue;const fp=fingerprint([file.name,file.type,file.text]);let remoteId=ctx.data.files[file.id],prev=ctx.data.fingerprints.files[file.id];if(remoteId&&prev&&prev!==fp){try{const remote=await jsonFetch(apiUrl(base,`/api/files/${encodeURIComponent(remoteId)}`),{method:'PUT',body:fileForm(file)});remoteId=remote.id;ctx.data.files[file.id]=remoteId;ctx.data.fingerprints.files[file.id]=fp;persist(ctx)}catch(e){console.warn('[Python AI] edição de arquivo pendente:',e.message);continue}}if(!remoteId){try{const remote=await jsonFetch(apiUrl(base,'/api/files'),{method:'POST',body:fileForm(file)});remoteId=remote.id;ctx.data.files[file.id]=remoteId;ctx.data.fingerprints.files[file.id]=fp;persist(ctx)}catch(e){console.warn('[Python AI] arquivo não sincronizado:',e.message);continue}}else if(!prev){ctx.data.fingerprints.files[file.id]=fp;persist(ctx)}remoteIds.push(remoteId);if(remoteIds.length>=20)break}return remoteIds}
function requestSelection(state){const cid=state.activeConversationId,api=window.PythonAIContextSelection,selected=api?.getForConversation?.(cid);return{conversationId:cid,fileIds:Array.isArray(selected?.fileIds)?selected.fileIds:[],useMemory:selected?.useMemory!==false}}
async function enrichChatRequest(url,options){const state=readState();if(!state)return{options,selection:null};const body=safeJson(options?.body||'');if(!body||!Array.isArray(body.messages))return{options,selection:null};const parsed=new URL(url,location.href),base=parsed.origin+parsed.pathname.replace(/\/api\/chat\/stream$/,''),ctx=bucket(base),selection=requestSelection(state);try{await reconcileDeleted(base,state,ctx);const conversationId=await ensureConversation(base,state,ctx);await syncMessages(base,state,ctx,conversationId);await syncMemories(base,state,ctx);const fileIds=await syncSelectedFiles(base,state,ctx,selection.fileIds);const enriched={...body,conversation_id:conversationId||null,file_ids:fileIds,use_memory:selection.useMemory};return{options:{...options,body:JSON.stringify(enriched)},selection}}catch(e){console.warn('[Python AI] sincronização de contexto indisponível; usando requisição original:',e.message);return{options,selection:null}}}
function consumeSelection(selection){if(!selection?.conversationId||!selection.fileIds?.length)return;window.PythonAIContextSelection?.consumeForConversation?.(selection.conversationId,selection.fileIds)}
async function observeStream(response){try{const text=await response.clone().text();for(const block of text.split('\n\n')){const line=block.split('\n').find(x=>x.startsWith('data:'));if(!line)continue;const data=safeJson(line.slice(5).trim());if(data?.context)window.PythonAIBackendSync.lastContext=data.context;if(data?.provider)window.PythonAIBackendSync.lastProvider=data.provider}window.dispatchEvent(new CustomEvent('python-ai-backend-context',{detail:{context:window.PythonAIBackendSync.lastContext||null,provider:window.PythonAIBackendSync.lastProvider||null}}))}catch{}}
window.PythonAIBackendSync={version:'1.6.0',lastContext:null,lastProvider:null,clear(){localStorage.removeItem(SYNC_KEY)}};
window.fetch=async function(input,options={}){const url=typeof input==='string'?input:input?.url||'',isChat=/\/api\/chat\/stream(?:\?|$)/.test(url)&&String(options.method||'GET').toUpperCase()==='POST';let next=options,selection=null;if(isChat){const enriched=await enrichChatRequest(url,options);next=enriched.options;selection=enriched.selection}const response=await nativeFetch(input,next);if(isChat&&response.ok){consumeSelection(selection);observeStream(response)}return response};
})();
