(()=>{'use strict';
const STORE='python-ai-definitive-v3';
function readState(){try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch{return {}}}
function relevantFiles(text){const s=readState(),terms=String(text||'').toLowerCase().split(/\W+/).filter(x=>x.length>3).slice(0,10),active=s.activeProjectId||null;return (s.files||[]).filter(f=>f.text&&(!active||f.projectId===active)).map(f=>({f,score:terms.reduce((n,t)=>n+(String(f.name).toLowerCase().includes(t)?3:0)+(String(f.text).toLowerCase().includes(t)?1:0),0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,3).map(x=>`Arquivo ${x.f.name}:\n${String(x.f.text).slice(0,4000)}`).join('\n\n')}
function augmentMessages(messages){if(!Array.isArray(messages))return messages;const user=[...messages].reverse().find(m=>m.role==='user')?.content||'',ctx=relevantFiles(user);if(!ctx)return messages;const out=messages.map(m=>({...m})),i=out.findIndex(m=>m.role==='system');const extra='\n\nTrechos de arquivos possivelmente relevantes:\n'+ctx;if(i>=0)out[i].content=String(out[i].content||'')+extra;else out.unshift({role:'system',content:extra.trim()});return out}
document.addEventListener('click',e=>{const scrim=e.target.closest('.scrim,[data-action="close-menu"]');if(scrim){document.querySelector('.side')?.classList.remove('open');document.querySelector('.scrim')?.classList.remove('show')}},true);
document.addEventListener('contextmenu',e=>{const row=e.target.closest('[data-chat]');if(!row)return;e.preventDefault();const s=readState(),id=row.dataset.chat;if(!id||!(s.conversations||[]).some(c=>c.id===id))return;if((s.conversations||[]).length<=1)return alert('Mantenha pelo menos uma conversa.');if(!confirm('Excluir esta conversa?'))return;s.conversations=s.conversations.filter(c=>c.id!==id);if(s.activeConversationId===id)s.activeConversationId=s.conversations[0]?.id||null;localStorage.setItem(STORE,JSON.stringify(s));location.reload()});
const realFetch=window.fetch.bind(window);window.fetch=async(input,init={})=>{try{const url=typeof input==='string'?input:input?.url||'';if(init?.body&&(/\/api\/chat|chat\/completions/.test(url))){const body=JSON.parse(init.body);if(body.messages)body.messages=augmentMessages(body.messages);init={...init,body:JSON.stringify(body)}}}catch{}return realFetch(input,init)};
function wrapChromeAI(){const LM=window.LanguageModel;if(!LM?.create||LM.__pythonAIWrapped)return;const original=LM.create.bind(LM);LM.create=async opts=>{const session=await original(opts),p=session.prompt?.bind(session),ps=session.promptStreaming?.bind(session);if(p)session.prompt=input=>{const ctx=relevantFiles(input);return p(ctx?input+'\n\nContexto de arquivos:\n'+ctx:input)};if(ps)session.promptStreaming=input=>{const ctx=relevantFiles(input);return ps(ctx?input+'\n\nContexto de arquivos:\n'+ctx:input)};return session};LM.__pythonAIWrapped=true}
wrapChromeAI();
})();
